<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>
<ul>
	<h2>Create</h2>
	<li><a href="<?php echo $this->url(array('controller' => 'employee', 'action' => 'create')); ?>">Employee</a></li>
	<li><a href="<?php echo $this->url(array('controller' => 'manager', 'action' => 'create')); ?>">Manager</a></li>
	<li><a href="<?php echo $this->url(array('controller' => 'project', 'action' => 'create')); ?>">Project</a></li>		
</ul>

<ul>
	<h2>Read</h2>
	<li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'read')); ?>">Users</a></li>
	<li><a href="<?php echo $this->url(array('controller' => 'employee', 'action' => 'read')); ?>">Employees</a></li>
	<li><a href="<?php echo $this->url(array('controller' => 'manager', 'action' => 'read')); ?>">Managers</a></li>
	<li><a href="<?php echo $this->url(array('controller' => 'project', 'action' => 'read')); ?>">Projects</a></li>
</ul>

<ul>
	<h2>Update</h2>
	<li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'update')); ?>">Users</a></li>
	<li><a href="<?php echo $this->url(array('controller' => 'employee', 'action' => 'update')); ?>">Employees</a></li>
	<li><a href="<?php echo $this->url(array('controller' => 'manager', 'action' => 'update')); ?>">Managers</a></li>
	<li><a href="<?php echo $this->url(array('controller' => 'project', 'action' => 'update')); ?>">Projects</a></li></ul>

<ul>
	<h2>Delete</h2>
	<li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'delete')); ?>">Users</a></li>
	<li><a href="<?php echo $this->url(array('controller' => 'employee', 'action' => 'delete')); ?>">Employees</a></li>
	<li><a href="<?php echo $this->url(array('controller' => 'manager', 'action' => 'delete')); ?>">Managers</a></li>
	<li><a href="<?php echo $this->url(array('controller' => 'project', 'action' => 'delete')); ?>">Projects</a></li>
</ul>